name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x

    - name: Restore dependencies
      run: dotnet restore LearnAi/TrivAiWeb.sln

    - name: Build
      run: dotnet build LearnAi/TrivAiWeb.sln --no-restore --configuration Release

    - name: Test
      run: dotnet test LearnAi/TrivAiWeb.sln --no-build --configuration Release --verbosity normal
